services:

  localstack:
    container_name: 'localstack'
    image: 'localstack/localstack:4.10.0'
    ports:
      - '127.0.0.1:4510-4559:4510-4559'  # external service port range
      - '127.0.0.1:4566:4566'            # LocalStack Edge Proxy
    security_opt:
      - 'label=disable'  # in Podman's configuration disables SELinux labeling enforcement for the container, which allows the container to access host resources without SELinux restrictions.
    environment:
      - 'LOCALSTACK_HOSTNAME=localhost.localstack.cloud'  # set this env var to expose localstack to other containers
      - 'AWS_ACCESS_KEY_ID=key'
      - 'AWS_SECRET_ACCESS_KEY=secret'
      - 'AWS_DEFAULT_REGION=eu-west-1'
      - 'SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,ec2,iam,kinesis,lambda,logs,s3,secretsmanager,ses,sns,sqs,ssm,sts,events'
      # ---
      - 'DEBUG=${DEBUG-}'
    volumes:
      - '$PWD/tmp/localstack:/var/lib/localstack'
      - '$PWD/build/lambda/function:/shared'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      default:
        aliases:
          - 'localhost.localstack.cloud'   # set this network aliases to expose localstack to other containers